### ISSUE TITLE
t3 can not be accessed across namespaces

### ISSUE THREAD

**Issue by lilyhe123** [oracle/weblogic-kubernetes-operator#1084]
Have a wls domain 'domain3' running in namespace 'test1' by the operator and a k8s service for the wls cluster named 'domain3-cluster-cluster-1' is created . Then running a jms client from namespace 'default' with InitialContext URL `t3://domain3-cluster-cluster-1.test1.svc.cluster.local:8001` and got following error. I run this in a single-node k8s cluster so it didn't seem to be a network problem.
```
Timed out while attempting to establish connection to :t3://domain3-cluster-cluster-1.test1.svc.cluster.local:8001 [Root exception is java.io.IOException: Timed out while attempting to establish connection to :t3://domain3-cluster-cluster-1.test1.svc.cluster.local:8001]
 at weblogic.jndi.WLInitialContextFactoryDelegate.throwRetryException(WLInitialContextFactoryDelegate.java:467)
 at weblogic.jndi.WLInitialContextFactoryDelegate.getInitialContext(WLInitialContextFactoryDelegate.java:403)
 at weblogic.jndi.Environment.getContext(Environment.java:353)
 at weblogic.jndi.Environment.getContext(Environment.java:322)
 at weblogic.jndi.WLInitialContextFactory.getInitialContext(WLInitialContextFactory.java:131)
 at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
 at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
 at javax.naming.InitialContext.init(InitialContext.java:244)
 at javax.naming.InitialContext.<init>(InitialContext.java:216)
 at samples.JMSSender.getInitialContext(JMSSender.java:74)
 at samples.JMSSender.init(JMSSender.java:51)
 at samples.JMSSender.main(JMSSender.java:80)
Caused by: java.io.IOException: Timed out while attempting to establish connection to :t3://domain3-cluster-cluster-1.test1.svc.cluster.local:8001
 at weblogic.rjvm.ConnectionManager.bootstrap(ConnectionManager.java:367)
 at weblogic.rjvm.RJVMManager.findOrCreateRemoteInternal(RJVMManager.java:318)
 at weblogic.rjvm.RJVMManager.findOrCreate(RJVMManager.java:161)
 at weblogic.rjvm.RJVMFinder.findOrCreateRemoteServer(RJVMFinder.java:258)
 at weblogic.rjvm.RJVMFinder.findOrCreateInternal(RJVMFinder.java:222)
 at weblogic.rjvm.RJVMFinder.findOrCreate(RJVMFinder.java:170)
 at weblogic.rjvm.ClientServerURL.findOrCreateRJVM(ClientServerURL.java:177)
 at weblogic.jndi.WLInitialContextFactoryDelegate$1.run(WLInitialContextFactoryDelegate.java:354)
 at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:368)
 at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:163)
 at weblogic.jndi.WLInitialContextFactoryDelegate.getInitialContext(WLInitialContextFactoryDelegate.java:350)
 ... 10 more
```

**Comment by tbarnes-us** [comment]
I think Shean Chang has already looked into this and come up with URL patterns that allow it.

**Comment by tbarnes-us** [comment]
@lilyhe123 - Per Pani, cross-namespace URLs need to be in the form (domain_uid)-(server_name).(namespace-for-the-domain_uid).svc.cluster.local for pods, which looks similar to the pod url you specified.  Can you double check that the name-space & service-name are correct, and also try a pod url instead of a cluster url to see if it works?

**Comment by shean-guangchang** [comment]
post your config.xml for the domain3 and which default channel or custom channel is serving port 8001?

**Comment by feiwwang** [comment]
Check bug 29344340.

**Comment by shean-guangchang** [comment]
the bug 29344340 is closed already.  I am asking the config.xml for the lily's case.  Is it the same as bug 29344340?  If yes, then please mark this as resolved.  Thanks!

**Comment by lilyhe123** [comment]
Part of the config.xml related to the cluster:
```
 <server-template>
    <name>template1</name>
    <ssl>
      <name>template1</name>
      <enabled>false</enabled>
      <listen-port>8100</listen-port>
    </ssl>
    <listen-port>8001</listen-port>
    <cluster>cluster-1</cluster>
  </server-template>
  <cluster>
    <name>cluster-1</name>
    <cluster-messaging-mode>unicast</cluster-messaging-mode>
    <client-cert-proxy-enabled>true</client-cert-proxy-enabled>
    <dynamic-servers>
      <name>NO_NAME_0</name>
      <server-template>template1</server-template>
      <calculated-listen-ports>false</calculated-listen-ports>
      <server-name-prefix>managed-server-</server-name-prefix>
      <dynamic-cluster-size>2</dynamic-cluster-size>
      <max-dynamic-cluster-size>2</max-dynamic-cluster-size>
    </dynamic-servers>
  </cluster>
```

**Comment by lilyhe123** [comment]
I tried URL pattern (domain_uid)-(server_name).(namespace-for-the-domain_uid).svc.cluster.local but still the same error.
And I also tried the server pod IP but didn't work either.

**Comment by feiwwang** [comment]
The magic of bug 29344340 seems to be setting the ExternalDNSName for the servers.

Here is Pani's comment:
The sequence of bringing domain does not matter,  the external-listen address 
MUST be set to the fully qualified service name of the local domain. 

The test uses the py scripts packaged with sample which should be modified as 
follows 
--- 
set('ExternalDNSName', 
'domain1-adminserver.weblogic-domain1.svc.cluster.local') 
--- 

This may be achieved by setting a env variable for NAMESPACE in 
create-domain-job-template.yaml and use the variable create-domain.py script 
to set the ExternalDNSName 


You may set ExternalDNSName for your AdminServer/ServerTemplate and see if it works.
