### ISSUE TITLE
SSL Enabled: false

### ISSUE THREAD

**Issue by dborysenko** [oracle/weblogic-kubernetes-operator#1457]
Setting "SSL enabled: false" causing introspectDomain.py script to fail with NullPointerException.

my wdt model:
```yaml
topology:
    AdminServerName: AdminServer
    Name: domain1
    ProductionModeEnabled: true
    Cluster:
        osb_cluster_1:
    Server:
        AdminServer:
            NetworkAccessPoint:
                T3Channel:
                    ListenPort: 30012
                    PublicAddress: "myexamplehost.us-east-2.eks.amazonaws.com"
                    PublicPort: 30012
            SSL:
                Enabled: false
                ListenPort: 7002
                HostnameVerificationIgnored: true
                ServerPrivateKeyPassPhraseEncrypted: 'passphrasechanged'
                JSSEEnabled: true
                ServerPrivateKeyAlias: DemoIdentity
        osb_server1:
            Cluster: osb_cluster_1
            ListenPort: 8001
            NumOfRetriesBeforeMsiMode: 0
            RetryIntervalBeforeMsiMode: 1
            JTAMigratableTarget:
                Cluster: osb_cluster_1
                UserPreferredServer: osb_server1
            CustomIdentityKeyStoreType: jks
            CustomIdentityKeyStoreFileName: wlsdeploy/servers/osb_server1/DemoIdentity.jks
            CustomIdentityKeyStorePassPhraseEncrypted: 'passphrasechanged'
            CustomTrustKeyStorePassPhraseEncrypted: 'passphrasechanged'
            CustomTrustKeyStoreType: jks
            CustomTrustKeyStoreFileName: wlsdeploy/servers/osb_server1/myTrust.jks
            ListenPort: 8011
            SSL:
                Enabled: false
                ListenPort: 7002
                HostnameVerificationIgnored: true
                ServerPrivateKeyPassPhraseEncrypted: 'passphrasechanged'
                JSSEEnabled: true
                ServerPrivateKeyAlias: DemoIdentity
    MigratableTarget:
        'osb_server1 (migratable)':
            Cluster: osb_cluster_1
            UserPreferredServer: osb_server1
```

exception during introspect phase:
```
@[2020-03-02T22:59:21.105 UTC][startNodeManager.sh:131][FINE] NODEMGR_HOME='/u01/nodemanager/domain1/introspector'
@[2020-03-02T22:59:21.117 UTC][startNodeManager.sh:132][FINE] LOG_HOME='/shared/logs/domain1'
@[2020-03-02T22:59:21.139 UTC][startNodeManager.sh:133][FINE] SERVER_NAME='introspector'
@[2020-03-02T22:59:21.159 UTC][startNodeManager.sh:134][FINE] DOMAIN_UID='domain1'
@[2020-03-02T22:59:21.172 UTC][startNodeManager.sh:135][FINE] NODEMGR_LOG_HOME='/shared/logs/domain1'
@[2020-03-02T22:59:21.190 UTC][startNodeManager.sh:136][FINE] FAIL_BOOT_ON_SITUATIONAL_CONFIG_ERROR='true'
@[2020-03-02T22:59:21.255 UTC][startNodeManager.sh:226][FINE] NODEMGR_LOG_HOME='/shared/logs/domain1'
@[2020-03-02T22:59:21.280 UTC][startNodeManager.sh:226][FINE] nodemgr_log_file='/shared/logs/domain1/introspector_nodemanager.log'
@[2020-03-02T22:59:21.297 UTC][startNodeManager.sh:226][FINE] nodemgr_out_file='/shared/logs/domain1/introspector_nodemanager.out'
@[2020-03-02T22:59:21.309 UTC][startNodeManager.sh:226][FINE] nodemgr_lck_file='/shared/logs/domain1/introspector_nodemanager.log.lck'
@[2020-03-02T22:59:21.322 UTC][startNodeManager.sh:146][FINE] remove nodemanager .lck file
@[2020-03-02T22:59:21.351 UTC][startNodeManager.sh:326][FINE] Start the nodemanager, node manager home is '/u01/nodemanager/domain1/introspector', log file is '/shared/logs/domain1/introspector_nodemanager.log', out file is '/shared/logs/domain1/introspector_nodemanager.out'.
@[2020-03-02T22:59:24.407 UTC][startNodeManager.sh:356][FINE] Nodemanager started in 3 seconds.
@[2020-03-02T22:59:24.417 UTC][introspectDomain.sh:372][FINE] Placing MD5 checksum of current domain secret 'DOMAIN_HOME/security/SerializedSystemIni.dat' in file '/tmp/DomainSecret.md5'.
@[2020-03-02T22:59:24.434 UTC][introspectDomain.sh:131][FINE] Running introspector WLST script /weblogic-operator/scripts/introspectDomain.py
@[2020-03-02T22:59:24.448 UTC][wlst.sh:28][FINE] About to run wlst script '/weblogic-operator/scripts/introspectDomain.py'
@[2020-03-02T22:59:24.458 UTC][wlst.sh:226][FINE] JAVA_HOME='/usr/java/default'
@[2020-03-02T22:59:24.467 UTC][wlst.sh:226][FINE] ORACLE_HOME='/u01/oracle'
@[2020-03-02T22:59:24.477 UTC][wlst.sh:226][FINE] WL_HOME='/u01/oracle/wlserver'
@[2020-03-02T22:59:24.486 UTC][wlst.sh:226][FINE] MW_HOME='/u01/oracle'
@[2020-03-02T22:59:24.495 UTC][wlst.sh:48][FINE] Running wlst script '/weblogic-operator/scripts/introspectDomain.py'
Initializing WebLogic Scripting Tool (WLST) ...
Welcome to WebLogic Server Administration Scripting Shell
Type help() for help on available commands
@[2020-03-02T22:59:44.631 UTC][introspectDomain.py:164][FINE] About to load domain from /shared/domains/domain1
@[2020-03-02T22:59:57.891 UTC][introspectDomain.py:1244][SEVERE] Domain introspection unexpectedly failed:
Traceback (most recent call last):
  File "/weblogic-operator/scripts/..2020_03_02_22_59_19.865188204/introspectDomain.py", line 1231, in main
    DomainIntrospector(env).introspect()
  File "/weblogic-operator/scripts/..2020_03_02_22_59_19.865188204/introspectDomain.py", line 1212, in introspect
    if tg.validate():
  File "/weblogic-operator/scripts/..2020_03_02_22_59_19.865188204/introspectDomain.py", line 316, in validate
    self.validateClusters()
  File "/weblogic-operator/scripts/..2020_03_02_22_59_19.865188204/introspectDomain.py", line 373, in validateClusters
    self.validateCluster(cluster)
  File "/weblogic-operator/scripts/..2020_03_02_22_59_19.865188204/introspectDomain.py", line 377, in validateCluster
    self.validateNonDynamicCluster(cluster)
  File "/weblogic-operator/scripts/..2020_03_02_22_59_19.865188204/introspectDomain.py", line 387, in validateNonDynamicCluster
    self.validateNonDynamicClusterServersHaveSameListenPort(cluster)
  File "/weblogic-operator/scripts/..2020_03_02_22_59_19.865188204/introspectDomain.py", line 441, in validateNonDynamicClusterServersHaveSameListenPort
    sslListenPort = ssl.getListenPort()
java.lang.NullPointerException: java.lang.NullPointerException
 
Exiting WebLogic Scripting Tool.
@[2020-03-02T22:59:57.937 UTC][wlst.sh:56][SEVERE] WLST script '/weblogic-operator/scripts/introspectDomain.py' failed with exit code '1'.
```

If you change SSL enabled to "true":
```yaml
            SSL:
                Enabled: true
```
 introspect phase completes successfully.

**Comment by vanajamukkara** [comment]
Hi @dborysenko, can you please provide the steps you followed to create the domain? also what version of WebLogic Kubernetes Operator are you using?

**Comment by dborysenko** [comment]
Hi @vanajamukkara ,
Thanks a lot for your quick response.
Below you can find detailed steps to reproduce described issue. Please take a look and let me know if any step is confusing or not clear.

1. Install operator 2.5
2. Clone operator
git clone https://github.com/oracle/weblogic-kubernetes-operator.git

3. Prepare namespace resources
kubectl create namespace domain1
kubectl -n domain1 create secret generic domain1-weblogic-credentials --from-literal=username=weblogic --from-literal=password=q1w2e3
kubectl label secret domain1-weblogic-credentials -n domain1 weblogic.domainUID=domain1 weblogic.domainName=domain1
kubectl -n domain1 create secret generic domain1-rcu-credentials --from-literal=username=Oradoc_db1 --from-literal=password=Oradoc_db1 --from-literal=sys_username=sys --from-literal=sys_password=Oradoc_db1
kubectl create secret docker-registry odr -n domain1 --docker-server=container-registry.oracle.com --docker-username=yourname@example.com --docker-password=secret --docker-email=yourname@example.com

4. Create RCU schema:
cd weblogic-kubernetes-operator/kubernetes/samples/scripts/create-rcu-schema
./create-rcu-schema.sh -s domain1 -p odr -d oracle-db.default.svc.cluster.local:1521/devpdb.k8s -i container-registry.oracle.com/middleware/soasuite:12.2.1.3

5. Prepare domain configs
cd weblogic-kubernetes-operator/kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-on-pv
edit create-domain-inputs.yaml: 
**a. change createDomainFilesDir from wlst to wdt**
b. adjust database connection string
c. change namespace to domain1
d. change imagePullSecretName to odr

6. Create domain
./create-domain.sh -i create-domain-inputs.yaml -o /tmp
kubectl apply -f /tmp/weblogic-domains/domain1/domain.yaml

7. Wait for introspect phase complete. Confirm adminserver has been started which confirms domain has been created successfully.

8. Delete domain
kubectl delete -f /tmp/weblogic-domains/domain1/domain.yaml
clear pvc
drop database
recreate rcu schema

9. Add SSL key to wdt model, edit weblogic-kubernetes-operator/kubernetes/samples/scripts/create-fmw-infrastructure-domain/domain-home-on-pv/wdt/wdt_model_configured.yaml
```yaml
        '@@PROP:managedServerNameBase@@1':
            Cluster: '@@PROP:clusterName@@'
            ListenPort: '@@PROP:managedServerPort@@'
            NumOfRetriesBeforeMsiMode: 0
            RetryIntervalBeforeMsiMode: 1
            JTAMigratableTarget:
                Cluster: '@@PROP:clusterName@@'
                UserPreferredServer: '@@PROP:managedServerNameBase@@1'
            SSL:
                Enabled: false
                ListenPort: 7123
                HostnameVerificationIgnored: true
                JSSEEnabled: true
```
10. Create domain
./create-domain.sh -i create-domain-inputs.yaml -o /tmp
kubectl apply -f  /tmp/weblogic-domains/domain1/domain.yaml

Check introspect pod stdout. It will fail with below errors on stdout:
```
@[2020-03-03T22:03:53.835 UTC][wlst.sh:48][FINE] Running wlst script '/weblogic-operator/scripts/introspectDomain.py'
Initializing WebLogic Scripting Tool (WLST) ...
Welcome to WebLogic Server Administration Scripting Shell
Type help() for help on available commands
@[2020-03-03T22:04:07.687 UTC][introspectDomain.py:164][FINE] About to load domain from /shared/domains/domain1
@[2020-03-03T22:04:17.305 UTC][introspectDomain.py:1244][SEVERE] Domain introspection unexpectedly failed:
Traceback (most recent call last):
  File "/weblogic-operator/scripts/..2020_03_03_22_03_48.031234505/introspectDomain.py", line 1231, in main
    DomainIntrospector(env).introspect()
  File "/weblogic-operator/scripts/..2020_03_03_22_03_48.031234505/introspectDomain.py", line 1212, in introspect
    if tg.validate():
  File "/weblogic-operator/scripts/..2020_03_03_22_03_48.031234505/introspectDomain.py", line 316, in validate
    self.validateClusters()
  File "/weblogic-operator/scripts/..2020_03_03_22_03_48.031234505/introspectDomain.py", line 373, in validateClusters
    self.validateCluster(cluster)
  File "/weblogic-operator/scripts/..2020_03_03_22_03_48.031234505/introspectDomain.py", line 377, in validateCluster
    self.validateNonDynamicCluster(cluster)
  File "/weblogic-operator/scripts/..2020_03_03_22_03_48.031234505/introspectDomain.py", line 387, in validateNonDynamicCluster
    self.validateNonDynamicClusterServersHaveSameListenPort(cluster)
  File "/weblogic-operator/scripts/..2020_03_03_22_03_48.031234505/introspectDomain.py", line 441, in validateNonDynamicClusterServersHaveSameListenPort
    sslListenPort = ssl.getListenPort()
java.lang.NullPointerException: java.lang.NullPointerException
 
Exiting WebLogic Scripting Tool.
@[2020-03-03T22:04:17.356 UTC][wlst.sh:56][SEVERE] WLST script '/weblogic-operator/scripts/introspectDomain.py' failed with exit code '1'.
```

**Comment by vanajamukkara** [comment]
Thanks for the detailed steps. We will try to reproduce the issue and get back to you.

**Comment by tbarnes-us** [comment]
The work-around for now is to avoid specifying the SSL clause in its entirety when it isn't needed (when SSLEnabled is false).

**Comment by ddsharpe** [comment]
@ dborysenko please confirm that when you leave the SSL section out of the WDT model that you no longer see the NPE.

**Comment by dborysenko** [comment]
@ddsharpe I do confirm. Basically the steps I've provided earlier confirm that as long as your wdt model does not have SSL section everything works. And it stops working if you put SSL section with  Enabled: false flag.

**Comment by tbarnes-us** [comment]
Pull request with fix under review:  https://github.com/oracle/weblogic-kubernetes-operator/pull/1631

**Comment by tbarnes-us** [comment]
Oops! The issue has long been resolved. I should have closed it almost a year ago!
