### ISSUE TITLE
Introspector job fails in Adding Log to ServerTemplate...

### ISSUE THREAD

**Issue by csegedicsaba** [oracle/weblogic-kubernetes-operator#2427]
From version **3.2.3** introspector job fails.  (3.2.2 is working fine)
We are using **model-in-image** method and we are specifying **spec.logHome** in Domain resource.

####<Jun 25, 2021 1:51:31 PM> <INFO> <TopologyUpdater> <_add_model_elements> <WLSDPLY-09602> <Adding Log to ServerTemplate xyz-cluster-template>
Problem invoking WLST - Traceback (innermost last):
  File "/u01/wdt/weblogic-deploy/lib/python/update.py", line 345, in ?
  File "/u01/wdt/weblogic-deploy/lib/python/update.py", line 330, in main
  File "/u01/wdt/weblogic-deploy/lib/python/update.py", line 107, in __update
  File "/u01/wdt/weblogic-deploy/lib/python/update.py", line 228, in __update_offline
  File "/u01/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/topology_updater.py", line 110, in update
  File "/u01/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/topology_updater.py", line 156, in _process_section
  File "/u01/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/topology_updater.py", line 64, in _add_named_elements
  File "/u01/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/deployer.py", line 95, in _add_named_elements
  File "/u01/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/deployer.py", line 155, in _set_attributes_and_add_subfolders
  File "/u01/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/deployer.py", line 117, in _add_subfolders
  File "/u01/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/topology_updater.py", line 68, in _add_model_elements
  File "/u01/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/deployer.py", line 143, in _add_model_elements
  File "/u01/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/deployer.py", line 154, in _set_attributes_and_add_subfolders
  File "/u01/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/deployer.py", line 179, in set_attributes
  File "/u01/wdt/weblogic-deploy/lib/python/wlsdeploy/tool/deploy/deployer_utils.py", line 339, in extract_from_uri
	at java.net.URI$Parser.fail(URI.java:2847)
	at java.net.URI$Parser.checkChars(URI.java:3020)
	at java.net.URI$Parser.parseHierarchical(URI.java:3104)
	at java.net.URI$Parser.parse(URI.java:3062)
	at java.net.URI.<init>(URI.java:588)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

java.net.URISyntaxException: java.net.URISyntaxException: Illegal character in path at index 43: /shared/logs/xyz-domain//managed-server-${id}.log

**Comment by anpanigr** [comment]
Is your logHome on PV ? Can you please share your model file.

**Comment by csegedicsaba** [comment]
Yes, logHome is on PV.
Here is a sample which fails with 3.2.3+:
https://github.com/csegedicsaba/wko-log-bug

**Comment by anpanigr** [comment]
Can use the weblogic image from  container-registry.oracle.com/middleware/weblogic:12.2.1.4
as described in the doc  https://oracle.github.io/weblogic-kubernetes-operator/quickstart/get-images/

I see you are using weblogic image from store/oracle/weblogic:12.2.1.4-dev-200117

**Comment by csegedicsaba** [comment]
Same issue with container-registry.oracle.com/middleware/weblogic:12.2.1.4 image.

**Comment by ddsharpe** [comment]
I see an issue in WDT that was fixed that looks similar.  What version of WDT is being used?

**Comment by tbarnes-us** [comment]
@csegedicsaba , I assume the issue has been resolved?  

If it hasn't, please try slack or re-open this issue.  

See [ > User Guide > Introduction > Get help](https://oracle.github.io/weblogic-kubernetes-operator/userguide/introduction/get-help/)
