### ISSUE TITLE
Build operator failed

### ISSUE THREAD

**Issue by simon-meng-cn** [oracle/weblogic-kubernetes-operator#286]
I used the latest code to build operator. Ran command mvn -P integration-tests clean install, got following error

[INFO] Running oracle.kubernetes.operator.HealthCheckHelperTest
Exception in thread “Exec Stream Pumper” java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3236)
    at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
    at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
    at java.io.PrintStream.write(PrintStream.java:480)
    at org.apache.commons.exec.StreamPumper.run(StreamPumper.java:108)
    at java.lang.Thread.run(Thread.java:748)

**Comment by simon-meng-cn** [comment]
After this error message appears, the compilation process hangs.

**Comment by rjeberhard** [comment]
@simon-meng-cn, @russgold has refactored the HealthCheckHelperTests.  Can you please retry?

**Comment by simon-meng-cn** [comment]
I build the operator successfully with the latest code today. The issue is fixed.
