### ISSUE TITLE
4.0.6 - SourcePath source-path for .war application is not updated in manager-servers

### ISSUE THREAD

**Issue by good92** [oracle/weblogic-kubernetes-operator#4282]
i am facing an inconsistency between the source-path and the .war path - correct, when doing images updates of the application. 

When looking for my app file:
```
grep -rIn 'APP_OLD_VERSION.war'    
/u01/domains/my-application/config/config.xml:89:    <source-path>wlsdeploy/applications/APP_OLD_VERSION.war</source-path>


  <app-deployment>
    <name>APP</name>
    <target>my-cluster-x</target>
    <module-type>war</module-type>
    <source-path>wlsdeploy/applications/APP_OLD_VERSION.war</source-path>
  </app-deployment>
```

but /u01/domains/my-application/wlsdeploy/applications contains the correct new .war version.

I am using the wko 4.0.6, wdt 3.2.1 and wit 1.11.11;

I saw that in https://github.com/oracle/weblogic-toolkit-ui/releases/tag/v1.5.3 (not the latest, and not using it, using ArgoCD) is talking about an open issue dealing with it:

"Known Issues

    In the Model Design View when creating an App Deployment or Shared Library, changing the Source field back to an empty value
    results in a bogus error message about not removing the deployment from the archive file. This error is harmless so simply
    dismiss the error dialog and continue."

Which components versions (wko, wit, wdt) are involved by this issue?

I am planning to revert to wko 4.0.5

i saw also an error when the domain introspector is launched on the new version update:

Directory trace for CUSTOM_DIR=/u01/domains/app-application/wlsdeploy/custom (before)                                                              
│ app-application-introspector   ls -ld /u01/domains/app-application/wlsdeploy/custom/*:                                                                                                                                                     
│ app-application-introspector     ls: cannot access /u01/domains/app-application/wlsdeploy/custom/*: No such file or directory                                                                                                              
│ app-application-introspector   ls -ld /u01/domains/app-application/wlsdeploy/custom:                                                                                                                                                       
│ app-application-introspector     ls: cannot access /u01/domains/app-application/wlsdeploy/custom: No such file or directory                                                                                                                
│ app-application-introspector   ls -ld /u01/domains/app-application/wlsdeploy:                                                                                                                                                              
│ app-application-introspector     ls: cannot access /u01/domains/app-application/wlsdeploy: No such file or directory                                                                                                                       
│ app-application-introspector   ls -ld /u01/domains/app-application:                                                                                                                                                                        
│ app-application-introspector     drwxr-x--- 12 oracle root 214 Jun 21 08:47 /u01/domains/app-application                                                                                                                                   
│ app-application-introspector   ls -ld /u01/domains:                                                                                                                                                                                        
│ app-application-introspector     drwxr-xr-x 3 oracle root 29 Jun 21 08:46 /u01/domains                                                                                                                                                     
│ app-application-introspector   ls -ld /u01:                                                                                                                                                                                                
│ app-application-introspector     drwxrwxr-x 1 oracle root 60 Jun 21 08:46 /u01                                                                                                                                                             
│ app-application-introspector   ls -ld /:                                                                                                                                                                                                   
│ app-application-introspector     drwxr-xr-x 1 root root 119 Jun 21 08:46 /

**Comment by good92** [comment]
YAML 4 spaces indentation and quote around the application below appDeployments: Application: , seems to fix WLSDPLY-20035: updateDomain encountered

now facing 

WLSDPLY-05026: my-cluster-x-template is not one of the folder names allowed in model location topology:/Server/ServerTemplate. 
Valid names are WebServer, SingleSignOnServices, ServerDiagnosticConfig, DefaultFileStore, ServerStart, DataSource, COM, CoherenceMemberConfig,
 NetworkAccessPoint, TransactionLogJDBCStore, IIOP, ConfigurationProperty, SSL, ServerDebug, FederationServices, ExecuteQueue, Log, WebService, 
 JTAMigratableTarget, OverloadProtection

**Comment by robertpatrick** [comment]
@good92 I don't understand the issue.

The WKTUI issue has nothing to do with the underlying tools--it is related to the WKTUI and WebLogic Remote Console integration.  If you are not using WKTUI, this issue does not impact you.

If you are using the WDT model to submit a change to the application to point to a different WAR file, did you update the `SourcePath` for the application in the model file?  The managed servers get their configuration at startup from the admin server so I don't understand what you mean by the "SourcePath is not updated in the managed servers".  In terms of application deployment, the managed servers get a copy of the application WAR file pushed to them from the AdminServer.  What is the behavior you are seeing that led you to try to start looking at config.xml on the managed servers?

I suspect that the issue might be that you added a new application WAR file with a different name and forgot to update the model `SourcePath` element to account for the new file name.

**Comment by robertpatrick** [comment]
> WLSDPLY-05026: my-cluster-x-template is not one of the folder names allowed in model location topology:/Server/ServerTemplate.
Valid names are WebServer, SingleSignOnServices, ServerDiagnosticConfig, DefaultFileStore, ServerStart, DataSource, COM, CoherenceMemberConfig,
NetworkAccessPoint, TransactionLogJDBCStore, IIOP, ConfigurationProperty, SSL, ServerDebug, FederationServices, ExecuteQueue, Log, WebService,
JTAMigratableTarget, OverloadProtection

I would need to see the model to comment but it looks like your model is not valid.  If you are trying to specify the ServerTemplate for a particular server, it should look something like this:

```
topology:
    Server:
        myserver:
            ServerTemplate: mytemplate
    ServerTemplate:
        mytemplate:
            ListenPort: 8888
```

The error tells me that you probably don't have a value for the `ServerTemplate` attribute so WDT is trying to treat it as a folder because it looks something like this:

```
topology:
    Server:
        myserver:
            ServerTemplate:
```

**Comment by good92** [comment]
@robertpatrick Thanks, I did not changed the app name.
 After generating a new image with WDT, I only change the image version with the model.image.image[0] in a git repo GitOpsed by ArgoCD.

On WLSDPLY-05026, you are right, it is another indentation issue: ServerTemplate was under Server

it would be great to have cue YAML spec to validate the files.  https://cuelang.org/docs/integrations/yaml/

**Comment by good92** [comment]
i see also "[SEVERE] Online update failed (the Domain resource specified 'spec.configuration.model.onlineUpdate.enabled=true').
 Depending on the type of failure, the model may have an unsupported change, you may need to try an offline update, or you may need to shutdown the entire domain and then restart it."

checking https://oracle.github.io/weblogic-kubernetes-operator/managing-domains/model-in-image/runtime-updates/#online-update-handling-of-non-dynamic-weblogic-configuration-changes

**Comment by robertpatrick** [comment]
> YAML 4 spaces indentation and quote around the application below appDeployments: Application: , seems to fix WLSDPLY-20035: updateDomain encountered
> the indentation error is caused by example here: https://oracle.github.io/weblogic-kubernetes-operator/managing-domains/model-in-image/model-files/

@good92 I cannot reproduce this problem.  I copied and pasted the model into a YAML file and ran validateModel on it.

```
weblogic-deploy/bin/validateModel.sh -oracle_home $MW_HOME -method lax -model_file wkomodel.yaml
...
Issue Log for validateModel version 3.2.2-SNAPSHOT running WebLogic version 12.2.1.4.0.210930 offline mode:

Total:   SEVERE :    0  WARNING :    0

validateModel.sh completed successfully (exit code = 0)
```

**Comment by robertpatrick** [comment]
> It would be great to have CUE YAML specifications to validate the files. https://cuelang.org/docs/integrations/yaml/

@good92 Unfortunately, it is not that simple.  What is allowed depends on the WLS version/patch level and whether it is online versus offline.  Have you tried the modelHelp tool?

```
weblogic-deploy/bin/modelHelp.sh -oracle_home $MW_HOME topology:/Machine
...
Attributes and sub-folders for topology:/Machine

topology:
    Machine:
        'NM-1':
            Address: # delimited_string  (default='') -
            Notes:   # string            +

            NodeManager:
                # see /Machine/NodeManager


This bean represents a machine on which servers may be booted. 
A server is bound to a machine by calling to 'ServerMBean.setMachine()'. 
Although it is typical that one 'MachineMBean' refers to one 
physical machine and vice versa, it is possible to have a multihomed 
machine represented by multiple 'MachineMBeans'. The only restriction 
is that each 'MachineMBean' be configured with non-overlapping 
addresses. A configuration may contain one or more of 'MachineMBeans' 
which may be looked up by their logical names.
 


Issue Log for modelHelp version 3.2.2-SNAPSHOT running WebLogic version 12.2.1.4.0.210930 offline mode:

Total:   SEVERE :    0  WARNING :    0

modelHelp.sh completed successfully (exit code = 0)
```

**Comment by good92** [comment]
On YAML 4 spaces, I saw that there examples with 2 spaces indentations and 4 indentations in the documentation. 
I will retry with 2 spaces indentation.

I missed the weblogic-deploy/bin/modelHelp.sh, thanks.

**Comment by robertpatrick** [comment]
In terms of the YAML indention, the SnakeYAML parser is picky so it doesn't like it when one subsection uses 2 spaces and a peer subsection uses 4.  We don't really have much control over that but if you find samples that generate parse errors, please file separate issues to let us know.

@good92 We should focus on the application problem in this issue.  If there are new issues, I will ask you to create a separate issues if I feel they are not related.  

> offline updates, are used with spec.image change.

> The issue is that the SourcePath is correct in /aux/models/model.yaml
and in /u01/domains/dmt-application/config/config.xml, it seems not updated.
> It then produce the errors:

```
Deployment service servlet encountered an Exception while handling the deployment datatransfer message for request id "0" from server "managed-server1". 
Exception is: "java.io.IOException: Invalid source path : /u01/domains/my-application/wlsdeploy/applications/APP_OLD.war 

Deployment service servlet encountered an Exception while handling the deployment datatransfer message for request id "0" from server "managed-server2". 
Exception is: "java.io.IOException: Invalid source path : /u01/domains/my-application/wlsdeploy/applications/APP_OLD.war 
```

Can you provide me the steps needed (or some other way) to reproduce this issue?

**Comment by good92** [comment]
@robertpatrick it will be really hard to have simple way to reproduce, as i am using Terraform to create the argocd and apps of apps and argocd vault plugin.

On the oracle@app-application-admin-server
```
/aux/weblogic-deploy/bin/modelHelp.sh -oracle_home /u01/oracle/wlserver/server/ topology:/Machine
JDK version is 1.8.0_361-b09
JAVA_HOME = /u01/jdk
CLASSPATH = /aux/weblogic-deploy/lib/weblogic-deploy-core.jar:/u01/oracle/wlserver/server//wlserver/server/lib/weblogic.jar
JAVA_PROPERTIES = -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployLoggingConfig -Dpython.cachedir.skip=true -Dpython.console= 
/u01/jdk/bin/java -cp /aux/weblogic-deploy/lib/weblogic-deploy-core.jar:/u01/oracle/wlserver/server//wlserver/server/lib/weblogic.jar           -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployLoggingConfig -Dpython.cachedir.skip=true -Dpython.console=            -Dpython.path=/u01/oracle/wlserver/server//wlserver/common/wlst/modules/jython-modules.jar/Lib           org.python.util.jython           /aux/weblogic-deploy/lib/python/model_help.py -oracle_home /u01/oracle/wlserver/server/ topology:/Machine
Error: Could not find or load main class org.python.util.jython

```

i have the same issue with wko 4.0.5.

**error**
```
<Error> <Deployer> <BEA-149205> <Failed to initialize the application "APP" due to error 
weblogic.management.DeploymentException: Exception occured while downloading files
	at weblogic.deploy.internal.targetserver.datamanagement.AppDataUpdate.doDownload(AppDataUpdate.java:50)
	at weblogic.deploy.internal.targetserver.datamanagement.DataUpdate.download(DataUpdate.java:59)
	at weblogic.deploy.internal.targetserver.datamanagement.Data.prepareDataUpdate(Data.java:126)
	at weblogic.deploy.internal.targetserver.BasicDeployment.prepareDataUpdate(BasicDeployment.java:907)
	at weblogic.deploy.internal.targetserver.BasicDeployment.stageFilesForStatic(BasicDeployment.java:960)
	Truncated. see log file for complete stacktrace

Caused By: java.io.IOException: [DeploymentService:290066]Error occurred while downloading files from Administration Server for deployment request "0".
 Underlying error is: "[DeploymentService:290065]Deployment service servlet encountered an Exception while handling the deployment datatransfer message
 for request id "0" from server "managed-server2". Exception is: "Invalid source path : /u01/domains/app-application/wlsdeploy/applications/APP_OLD_VERSION.war"."
	at weblogic.deploy.service.datatransferhandlers.HttpDataTransferHandler.getDataAsStream(HttpDataTransferHandler.java:92)
	at weblogic.deploy.service.datatransferhandlers.DataHandlerManager$RemoteDataTransferHandler.getDataAsStream(DataHandlerManager.java:175)
	at weblogic.deploy.internal.targetserver.datamanagement.AppDataUpdate.doDownload(AppDataUpdate.java:46)
	at weblogic.deploy.internal.targetserver.datamanagement.DataUpdate.download(DataUpdate.java:59)
	at weblogic.deploy.internal.targetserver.datamanagement.Data.prepareDataUpdate(Data.java:126)
	Truncated. see log file for complete stacktrace 
```

**Comment by robertpatrick** [comment]
@good92 Likewise, it will be virtually impossible for us to help you based on little snippets of information.  My suggestion is to eliminate terraform and ArgoCD from the equation and try running the process manually.  Once we identify the issue and correct it, you can add back the automation software.

**Comment by robertpatrick** [comment]
@good92 As for the modelHelp error, notice the double slash in the path you provided?  This was a bug that has already been fixed.  You just need to upgrade WDT to the latest version.

**Comment by good92** [comment]
```
export WLSDEPLOY_HOME=/aux/weblogic-deploy;
export WLSDEPLOY_PROPERTIES=/aux/models;
/aux/weblogic-deploy/bin/modelHelp.sh -oracle_home /u01/oracle/wlserver/server topology:/Machine;

JDK version is 1.8.0_361-b09
JAVA_HOME = /u01/jdk
CLASSPATH = /aux/weblogic-deploy/lib/weblogic-deploy-core.jar:/u01/oracle/wlserver/server/wlserver/server/lib/weblogic.jar
JAVA_PROPERTIES = -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployLoggingConfig -Dpython.cachedir.skip=true -Dpython.console= /aux/models
/u01/jdk/bin/java -cp /aux/weblogic-deploy/lib/weblogic-deploy-core.jar:/u01/oracle/wlserver/server/wlserver/server/lib/weblogic.jar           -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployLoggingConfig -Dpython.cachedir.skip=true -Dpython.console= /aux/models           -Dpython.path=/u01/oracle/wlserver/server/wlserver/common/wlst/modules/jython-modules.jar/Lib           org.python.util.jython           /aux/weblogic-deploy/lib/python/model_help.py -oracle_home /u01/oracle/wlserver/server topology:/Machine
Error: Could not find or load main class .aux.models

modelHelp.sh completed but with some issues (exit code = 1)
```

**Comment by good92** [comment]
weblogic log

```
####<Jun 22, 2023 12:29:23,641 PM UTC> <Info> <JDBC> <dmt-application-managed-server1> <managed-server1> <[STANDBY] ExecuteThread: '1' for queue: 'weblogic.kernel.Default (self-tuning)'>
 <<WLS Kernel>> <> <d23e0595-3851-42db-97bb-5d4b83296325-00000008> <1687436963641> <[severity-value: 64] [rid: 0] [partition-id: 0] [partition-name: DOMAIN] > <BEA-001512> <Data source Quartz has been successfully created.> 
####<Jun 22, 2023 12:29:23,730 PM UTC> <Error> <Deployer> <dmt-application-managed-server1> <managed-server1> <[STANDBY] ExecuteThread: '1' for queue:
 'weblogic.kernel.Default (self-tuning)'> <<WLS Kernel>> <> <d23e0595-3851-42db-97bb-5d4b83296325-00000008> <1687436963730> <[severity-value: 8] [rid: 0] 
 [partition-id: 0] [partition-name: DOMAIN] > <BEA-149205> <Failed to initialize the application "APP" due to error weblogic.management.DeploymentException: Exception occured while downloading files
	at weblogic.deploy.internal.targetserver.datamanagement.AppDataUpdate.doDownload(AppDataUpdate.java:50)
	at weblogic.deploy.internal.targetserver.datamanagement.DataUpdate.download(DataUpdate.java:59)
	at weblogic.deploy.internal.targetserver.datamanagement.Data.prepareDataUpdate(Data.java:126)
	at weblogic.deploy.internal.targetserver.BasicDeployment.prepareDataUpdate(BasicDeployment.java:907)
	at weblogic.deploy.internal.targetserver.BasicDeployment.stageFilesForStatic(BasicDeployment.java:960)
	at weblogic.deploy.internal.targetserver.AppDeployment.prepare(AppDeployment.java:116)
	at weblogic.management.deploy.internal.DeploymentAdapter$1.doPrepare(DeploymentAdapter.java:41)
	at weblogic.management.deploy.internal.DeploymentAdapter.prepare(DeploymentAdapter.java:193)
	at weblogic.management.deploy.internal.AppTransition$1.transitionAppInternal(AppTransition.java:32)
	at weblogic.management.deploy.internal.AppTransition.transitionApp(AppTransition.java:138)
	at weblogic.management.deploy.internal.ConfiguredDeployments$2.doItem(ConfiguredDeployments.java:741)
	at weblogic.management.deploy.internal.parallel.BucketInvoker.invoke(BucketInvoker.java:138)
	at weblogic.management.deploy.internal.ConfiguredDeployments.transitionAppsParallel(ConfiguredDeployments.java:749)
	at weblogic.management.deploy.internal.ConfiguredDeployments.prepare(ConfiguredDeployments.java:363)
	at weblogic.management.deploy.internal.ConfiguredDeployments.deploy(ConfiguredDeployments.java:232)
	at weblogic.management.deploy.internal.DeploymentServerService.resume(DeploymentServerService.java:219)
	at weblogic.management.deploy.internal.DeploymentServerService.start(DeploymentServerService.java:133)
	at weblogic.server.AbstractServerService.postConstruct(AbstractServerService.java:76)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1287)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:333)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:698)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:78)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:212)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:235)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:681)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)

Caused By: java.io.IOException: [DeploymentService:290066]Error occurred while downloading files from Administration Server for deployment request "0". Underlying error is:
 "[DeploymentService:290065]Deployment service servlet encountered an Exception while handling the deployment datatransfer message for request id "0" from server "managed-server1".
 Exception is: "Invalid source path : /u01/domains/app-application/wlsdeploy/applications/APP_OLD.war"."
	at weblogic.deploy.service.datatransferhandlers.HttpDataTransferHandler.getDataAsStream(HttpDataTransferHandler.java:92)
	at weblogic.deploy.service.datatransferhandlers.DataHandlerManager$RemoteDataTransferHandler.getDataAsStream(DataHandlerManager.java:175)
	at weblogic.deploy.internal.targetserver.datamanagement.AppDataUpdate.doDownload(AppDataUpdate.java:46)
	at weblogic.deploy.internal.targetserver.datamanagement.DataUpdate.download(DataUpdate.java:59)
	at weblogic.deploy.internal.targetserver.datamanagement.Data.prepareDataUpdate(Data.java:126)
	at weblogic.deploy.internal.targetserver.BasicDeployment.prepareDataUpdate(BasicDeployment.java:907)
	at weblogic.deploy.internal.targetserver.BasicDeployment.stageFilesForStatic(BasicDeployment.java:960)
	at weblogic.deploy.internal.targetserver.AppDeployment.prepare(AppDeployment.java:116)
	at weblogic.management.deploy.internal.DeploymentAdapter$1.doPrepare(DeploymentAdapter.java:41)
	at weblogic.management.deploy.internal.DeploymentAdapter.prepare(DeploymentAdapter.java:193)
	at weblogic.management.deploy.internal.AppTransition$1.transitionAppInternal(AppTransition.java:32)
	at weblogic.management.deploy.internal.AppTransition.transitionApp(AppTransition.java:138)
	at weblogic.management.deploy.internal.ConfiguredDeployments$2.doItem(ConfiguredDeployments.java:741)
	at weblogic.management.deploy.internal.parallel.BucketInvoker.invoke(BucketInvoker.java:138)
	at weblogic.management.deploy.internal.ConfiguredDeployments.transitionAppsParallel(ConfiguredDeployments.java:749)
	at weblogic.management.deploy.internal.ConfiguredDeployments.prepare(ConfiguredDeployments.java:363)
	at weblogic.management.deploy.internal.ConfiguredDeployments.deploy(ConfiguredDeployments.java:232)
	at weblogic.management.deploy.internal.DeploymentServerService.resume(DeploymentServerService.java:219)
	at weblogic.management.deploy.internal.DeploymentServerService.start(DeploymentServerService.java:133)
	at weblogic.server.AbstractServerService.postConstruct(AbstractServerService.java:76)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1287)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:333)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:698)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:78)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:212)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:235)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:681)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)
```

**Comment by good92** [comment]
the log before sounds ok:
```
managed-server1 auxiliaryImageLogs]$ cat operator-aux-container1.out 
@[2023-06-22T12:28:01.%NZ][auxImage.sh:64][FINE] Auxiliary Image: About to copy WDT installation files from '/auxiliary/weblogic-deploy'  in container image='xxxxxxx.dkr.ecr.REGION.amazonaws.com/APP:NEW'. 
@[2023-06-22T12:28:01.%NZ][auxImage.sh:64][FINE] Creating folder '/tmpAuxiliaryImage/weblogic-deploy' using command 'mkdir -m 750 -p /tmpAuxiliaryImage/weblogic-deploy'. This is the target directory for WDT installation files.
@[2023-06-22T12:28:01.%NZ][auxImage.sh:64][FINE] Auxiliary Image: About to copy WDT model files from '/auxiliary/models'  in container image='xxxxxxxxx.dkr.ecr.REGION.amazonaws.com/APP:NEW'. 
@[2023-06-22T12:28:01.%NZ][auxImage.sh:64][FINE] Creating folder '/tmpAuxiliaryImage/models' using command 'mkdir -m 750 -p /tmpAuxiliaryImage/models'. This is the target directory for WDT model files.
@[2023-06-22T12:28:01.%NZ][auxImage.sh:64][FINE] Auxiliary Image: Commands executed successfully.
```

**Comment by robertpatrick** [comment]
Can you show us the admin server log file to see if it has anything more about why the download failed?

**Comment by jshum2479** [comment]
@good92  Are you using online or offline update - online update to deploy/update an application is not supported.   Can you check the domain resource YAML in memory to verify?  (e.g.  k get domain <id> -o yaml)     

i see also "[SEVERE] Online update failed (the Domain resource specified 'spec.configuration.model.onlineUpdate.enabled=true').
Depending on the type of failure, the model may have an unsupported change, you may need to try an offline update, or you may need to shutdown the entire domain and then restart it."

**Comment by good92** [comment]
application-introspector-vv8bl oracle]$ cat ps.log
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
oracle       1  0.2  0.0 119884  4112 ?        Ss   15:00   0:00 /bin/bash /weblogic-operator/scripts/introspectDomain.sh
oracle     556  0.2  0.0 120016  3840 ?        S    15:00   0:00 /bin/bash /weblogic-operator/scripts/introspectDomain.sh
oracle     557  0.0  0.0 109540  1724 ?        S    15:00   0:00 tee /tmp/introspector_script.out
oracle    1069  0.0  0.0 119096  3328 pts/0    Ss   15:00   0:00 bash
oracle    1383  0.0  0.0 119092  3272 ?        S    15:01   0:00 /bin/sh /aux/weblogic-deploy/bin/compareModel.sh -oracle_home /u01/oracle -output_dir /tmp /tmp/new_merged_model.json /tmp/decrypted_merged_model.json
oracle    1410 78.0  1.1 3888680 92592 ?       Sl   15:01   0:00 /u01/jdk/bin/java -cp /aux/weblogic-deploy/lib/weblogic-deploy-core.jar:/u01/oracle/wlserver/server/lib/weblogic.jar
 -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployLoggingConfig -Dpython.cachedir.skip=true -Dpython.console=
 -Dpython.path=/u01/oracle/wlserver/common/wlst/modules/jython-modules.jar/Lib org.python.util.jython /aux/weblogic-deploy/lib/python/compare_model.py 
 
 -oracle_home /u01/oracle -output_dir /tmp /tmp/new_merged_model.json /tmp/decrypted_merged_model.json
oracle    1420  0.0  0.0 156912  3760 pts/0    R+   15:01   0:00 ps -aux

**Comment by robertpatrick** [comment]
@good92 We need to see the WDT updateDomain.log file from the introspector pod.  While you are in there, please grab the entire `appDeployments` section of the model file.

**Comment by good92** [comment]
[oracle@APP-application-introspector-zzh8n oracle]$ cat /tmp/decrypted_merged_model.json
...
    "appDeployments" : {
        "Application" : {
            "DMTSec" : {
                "SourcePath" : "wlsdeploy/applications/APP_OLD.war",
                "ModuleType" : "war",
                "Target" : "mcluster-1"
            }
        }
    },
 ..

oracleAPP-application-introspector-8qqx5 oracle]$ cat /tmp/diffed_model.yaml;
appDeployments:
    Application:
        DMTSec:
            # SourcePath: 'wlsdeploy/applications/APP_OLD.war'
            SourcePath: wlsdeploy/applications/APP_NEW.war
            ModuleType: war
            Target: mcluster-1

**Comment by jshum2479** [comment]
You are using online update

application-introspector ####<Jun 22, 2023 1:57:47 PM> <INFO> <update> <__update_online> <WLSDPLY-09007> <Connected to domain at t3://app-application-admin-server:7001>                                                               │

Can you show 

 kubectl -n <ns> get domain <domain id> -o jsonpath="{.spec.configuration.model}"

**Comment by good92** [comment]
@jshum2479 yes, you are right.

**Comment by jshum2479** [comment]
You should try to disabled it when deploying/updating app from your new image.  A running pod will never have the bits from new image(s) until it is recycled.  You should use offline update (disable the onlineUpdate) instead.

**Comment by good92** [comment]
Many thanks it is now solved.
