### ISSUE TITLE
Impossible build WebLogic operator locally.

### ISSUE THREAD

**Issue by antonionappi88** [oracle/weblogic-kubernetes-operator#431]
Hello there,
I'm trying to build the operator locally( mvn clean installl) but I get always these errors : 

```[INFO] Running oracle.kubernetes.operator.builders.WatchBuilderTest
java.lang.NullPointerException
        at io.kubernetes.client.util.ClientBuilder.kubeconfig(ClientBuilder.java:148)
        at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:80)
        at io.kubernetes.client.util.Config.defaultClient(Config.java:104)
        at oracle.kubernetes.operator.helpers.ClientPool$DefaultClientFactory.get(ClientPool.java:71)
        at oracle.kubernetes.operator.helpers.ClientPool$DefaultClientFactory.get(ClientPool.java:64)
        at oracle.kubernetes.operator.helpers.ClientPool.getApiClient(ClientPool.java:51)
        at oracle.kubernetes.operator.helpers.ClientPool.create(ClientPool.java:33)
        at oracle.kubernetes.operator.helpers.ClientPool.create(ClientPool.java:19)
        at oracle.kubernetes.operator.helpers.Pool.take(Pool.java:29)
        at oracle.kubernetes.operator.builders.WatchBuilderTest$TestServerWatchFactory$1.create(WatchBuilderTest.java:334)
        at oracle.kubernetes.operator.builders.WatchBuilderTest$TestServerWatchFactory$1.create(WatchBuilderTest.java:328)
        at oracle.kubernetes.operator.helpers.Pool.take(Pool.java:29)
        at oracle.kubernetes.operator.builders.WatchBuilder$WatchFactoryImpl.createWatch(WatchBuilder.java:401)
        at oracle.kubernetes.operator.builders.WatchBuilderTest$TestServerWatchFactory.createWatch(WatchBuilderTest.java:342)
        at oracle.kubernetes.operator.builders.WatchBuilder.createIngressWatch(WatchBuilder.java:214)
        at oracle.kubernetes.operator.builders.WatchBuilderTest.whenIngressWatchSpecifiesParameters_verifyAndReturnResponse(WatchBuilderTest.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
```

and 

```
[ERROR] Errors: 
[ERROR] oracle.kubernetes.operator.builders.WatchBuilderTest.whenDomainWatchReceivesAddResponse_returnItFromIterator(oracle.kubernetes.operator.builders.WatchBuilderTest)
[ERROR]   Run 1: WatchBuilderTest.whenDomainWatchReceivesAddResponse_returnItFromIterator:86 » NullPointer
[ERROR]   Run 2: WatchBuilderTest.whenDomainWatchReceivesAddResponse_returnItFromIterator:86 » NullPointer
[INFO] 
[ERROR] oracle.kubernetes.operator.builders.WatchBuilderTest.whenDomainWatchReceivesErrorResponse_returnItFromIterator(oracle.kubernetes.operator.builders.WatchBuilderTest)
[ERROR]   Run 1: WatchBuilderTest.whenDomainWatchReceivesErrorResponse_returnItFromIterator:118 » NullPointer
[ERROR]   Run 2: WatchBuilderTest.whenDomainWatchReceivesErrorResponse_returnItFromIterator:118 » NullPointer
[INFO] 
[ERROR] oracle.kubernetes.operator.builders.WatchBuilderTest.whenDomainWatchReceivesModifyAndDeleteResponses_returnBothFromIterator(oracle.kubernetes.operator.builders.WatchBuilderTest)
[ERROR]   Run 1: WatchBuilderTest.whenDomainWatchReceivesModifyAndDeleteResponses_returnBothFromIterator:109 » NullPointer
[ERROR]   Run 2: WatchBuilderTest.whenDomainWatchReceivesModifyAndDeleteResponses_returnBothFromIterator:109 » NullPointer
[INFO] 
[ERROR] oracle.kubernetes.operator.builders.WatchBuilderTest.whenIngressWatchSpecifiesParameters_verifyAndReturnResponse(oracle.kubernetes.operator.builders.WatchBuilderTest)
[ERROR]   Run 1: WatchBuilderTest.whenIngressWatchSpecifiesParameters_verifyAndReturnResponse:199 » NullPointer
[ERROR]   Run 2: WatchBuilderTest.whenIngressWatchSpecifiesParameters_verifyAndReturnResponse:199 » NullPointer
[INFO] 
[ERROR] oracle.kubernetes.operator.builders.WatchBuilderTest.whenPodWatchFindsNoData_hasNextReturnsFalse(oracle.kubernetes.operator.builders.WatchBuilderTest)
[ERROR]   Run 1: WatchBuilderTest.whenPodWatchFindsNoData_hasNextReturnsFalse:175 » NullPointer
[ERROR]   Run 2: WatchBuilderTest.whenPodWatchFindsNoData_hasNextReturnsFalse:175 » NullPointer
[INFO] 
[ERROR] oracle.kubernetes.operator.builders.WatchBuilderTest.whenPodWatchSpecifiesParameters_verifyAndReturnResponse(oracle.kubernetes.operator.builders.WatchBuilderTest)
[ERROR]   Run 1: WatchBuilderTest.whenPodWatchSpecifiesParameters_verifyAndReturnResponse:166 » NullPointer
[ERROR]   Run 2: WatchBuilderTest.whenPodWatchSpecifiesParameters_verifyAndReturnResponse:166 » NullPointer
[INFO] 
[ERROR] oracle.kubernetes.operator.builders.WatchBuilderTest.whenServiceWatchSpecifiesParameters_verifyAndReturnResponse(oracle.kubernetes.operator.builders.WatchBuilderTest)
[ERROR]   Run 1: WatchBuilderTest.whenServiceWatchSpecifiesParameters_verifyAndReturnResponse:144 » NullPointer
[ERROR]   Run 2: WatchBuilderTest.whenServiceWatchSpecifiesParameters_verifyAndReturnResponse:144 » NullPointer
[INFO] 
[ERROR] oracle.kubernetes.operator.calls.AsyncRequestStepTest.afterFiberStarted_requestSent(oracle.kubernetes.operator.calls.AsyncRequestStepTest)
[ERROR]   Run 1: AsyncRequestStepTest.afterFiberStarted_requestSent:71
[ERROR]   Run 2: AsyncRequestStepTest.setUp:61 » NullPointer
[INFO] 
[ERROR] oracle.kubernetes.operator.calls.AsyncRequestStepTest.afterFiberStarted_timeoutStepScheduled(oracle.kubernetes.operator.calls.AsyncRequestStepTest)
[ERROR]   Run 1: AsyncRequestStepTest.afterFiberStarted_timeoutStepScheduled:76
[ERROR]   Run 2: AsyncRequestStepTest.setUp:61 » NullPointer
[INFO] 
[ERROR] oracle.kubernetes.operator.calls.AsyncRequestStepTest.afterSuccessfulCallback_nextStepAppliedWithValue(oracle.kubernetes.operator.calls.AsyncRequestStepTest)
[ERROR]   Run 1: AsyncRequestStepTest.afterSuccessfulCallback_nextStepAppliedWithValue:90 » NullPointer
[ERROR]   Run 2: AsyncRequestStepTest.setUp:61 » NullPointer
[INFO] 
[ERROR] oracle.kubernetes.operator.calls.AsyncRequestStepTest.afterSuccessfulCallback_packetDoesNotContainsResponse(oracle.kubernetes.operator.calls.AsyncRequestStepTest)
[ERROR]   Run 1: AsyncRequestStepTest.afterSuccessfulCallback_packetDoesNotContainsResponse:97->lambda$afterSuccessfulCallback_packetDoesNotContainsResponse$0:97 » NullPointer
[ERROR]   Run 2: AsyncRequestStepTest.setUp:61 » NullPointer
[INFO] 
[ERROR] oracle.kubernetes.operator.calls.AsyncRequestStepTest.afterTimeout_newRequestSent(oracle.kubernetes.operator.calls.AsyncRequestStepTest)
[ERROR]   Run 1: AsyncRequestStepTest.afterTimeout_newRequestSent:85
[ERROR]   Run 2: AsyncRequestStepTest.setUp:61 » NullPointer
[INFO] 
[INFO] 
[ERROR] Tests run: 520, Failures: 0, Errors: 12, Skipped: 10

```

Below all the required tools with version : 

``` docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
```java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

```mvn -version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: /home/anappi/Downloads/apache-maven-3.5.2
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-862.11.6.el7.x86_64", arch: "amd64", family: "unix"
```

```git version
git version 1.8.3.1
```

Do you know what i'm doing wrong ?
I just clone a clean repository and run mvn clean install.

Cheers,
Antonio

**Comment by moreaut** [comment]
Hi Antonio,

Which branch are you trying to build? master? develop? v1.1?

Thanks, -Tom

**Comment by antonionappi88** [comment]
Hi Tom,
I'm on the master branch.

Thanks.
Antonio

**Comment by moreaut** [comment]
Hi Antonio,

Have you installed docker and kubernetes, and are they up and running when you do your build?
And which versions of these did you install?

Have you followed the installation instructions in https://github.com/oracle/weblogic-kubernetes-operator/blob/master/site/installation.md ?

Also, is your ~/.kube/config file correct?

When I modified mine to comment out the 'server' lines, then I see the same stack trace you're seeing.

Thanks, -Tom

FYI - here's the ~/.kube/config I'm using on my mac (with the server lines not commented out):

apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6443
  name: docker-for-desktop-cluster
- cluster:
    certificate-authority-data: ...
    server: https://10.240.24.75:6443
  name: kubernetes
contexts:
- context:
    cluster: docker-for-desktop-cluster
    user: docker-for-desktop
  name: docker-for-desktop
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: docker-for-desktop
kind: Config
preferences: {}
users:
- name: docker-for-desktop
  user:
    client-certificate-data:  ...
    client-key-data:  ...
- name: kubernetes-admin
  user:
    client-certificate-data:  ...
    client-key-data:  ...

**Comment by moreaut** [comment]
[kube_config.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/2438143/kube_config.txt)

**Comment by antonionappi88** [comment]
Hi Tom,
I was following the section : **Build the Docker image for the operator locally**
Docker is up and running instead I don't have any kubernetes package installed( a part kubectl ). 
In the section that I was following there was not mention about it.  Do I need any particular library to build from source ?

Thanks 
Antonio

**Comment by moreaut** [comment]
Hi Antonio,

You need to install Kubernetes before building locally.

https://github.com/oracle/weblogic-kubernetes-operator/blob/master/site/k8s_setup.md ?

Thanks, -Tom

**Comment by antonionappi88** [comment]
Hi tom,

I usually have  ~/.kube/config in another directory. Exporting the KUBECONFIG with the correct path the `mvn clean install` worked without problems.

Thanks a lot!
Antonio

**Comment by moreaut** [comment]
Hi Antonio,

You're welcome, I'm glad I could help you out.

I'm curious - do you also have a ~/.kube/config file that doesn't have a 'server' entry in it?
I'm trying to understand why you got that particular stack trace before you exported KUBECONFIG.

Thanks, -Tom

**Comment by antonionappi88** [comment]
Hi Tom,

yes I have also a ~/.kube/config file that it looks like this : 

```
apiVersion: v1                              
clusters: []                                
contexts: []                                
current-context: ""                         
kind: Config                                
preferences: {}                             
users:                                      
- name: anappi                              
  user:                                     
    token: WHATEVER
```

Cheers,
Antonio

**Comment by moreaut** [comment]
Cool - that explains the NPE - it's not setting the 'server' property.
Mind if I close this issue?

**Comment by antonionappi88** [comment]
Hi Tom,
you can close it.
Thank you a lot.

Antonio
